spring:
  application:
    name: eTutor Task-App - Hierarchical Clustering
  messages:
    fallback-to-system-locale: false

  # Database
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  # Server
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    format:
      date-time: iso
    problemdetails:
      enabled: true

# Server
server:
  port: 8081

# API docs
springdoc:
  swagger-ui:
    path: /docs
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /api-docs

# Logging
logging:
  include-application-name: false
  logback:
    rollingpolicy:
      file-name-pattern: logs/task-app-hierarchical-clustering.%d{yyyy-MM-dd}.%i.log
      max-file-size: 50MB
      max-history: 14
  file:
    name: logs/task-app-hierarchical-clustering.log

# Actuator
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    os:
      enabled: true
    java:
      enabled: true
    git:
      mode: full
  endpoint:
    env:
      show-values: ALWAYS
    health:
      probes:
        enabled: true
      show-details: WHEN_AUTHORIZED
      show-components: WHEN_AUTHORIZED
      roles:
        - CRUD
  endpoints:
    web:
      exposure:
        include:
          - env
          - flyway
          - health
          - httpexchanges
          - info
          - logfile
          - metrics
          - livenessstate
          - readinessstate

# Custom parameter config
app:
  # Configs for matrix generation step and both coordinate generators separately
  generation:
    matrix:
      step: 0.5

    # Generation for manhattan distance is strictly faster, therefore separate config to allow separate setting of attempts
    coordinates:
      euclidean:
        restarts: 50
        max-attempts-per-point: 100_000
      manhattan:
        restarts: 150
        max-attempts-per-point: 200_000

  # Dendrogram layout and style
  dendrogram:
    canvas:
      width: 900
      height: 600
      margin:
        top: 40
        bottom: 60
        left: 70
        right: 30

    labels:
      leaf:
        font-size: 20
        offset: 5
      axis:
        font-size: 16
        tick-length: 5
        label-gap: 4

    lines:
      width: 2

    colors:
      label: "#222222"
      axis: "#303030"
      grid: "#B7BFC7"
      line: "#000000"
      background: "#ffffff"
